work-dir: /usr/local/etc/wpra
app-id: wx650000a0000r0000
app-secret: 0000ddf910b8dc0b6423456g0000d8d
http-server-listen: "127.0.0.1:8090"
base-url-path: /api/wechat
security-prefix: Wky9i86lKRJ5mhzIt4v1n2mKq2SQiL8
token: 21LcJJVRkGJtufk12FEQQoHDtQA9hrjG
template-id: 7jgu5kede8NToE3VbUA6x6yxyR5Jasdsaklrj1QKE
open-id: ojV3l57pR7dwtRXgliK6cff9J050